# IMPORTANT NOTE: The results of these benchmarks are not representative. This
# is simply a smoke test to check everything compiles and runs.

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'Benchmark/**'
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.f'
      - '**/*.F'
      - '**/*.f90'
      - '**/*.F90'

jobs:
  # Let us run this job on Ubuntu only as it is the only image that has gcc,
  # gfortran, and clang available out of the box
  multiple-compilers:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run multiple compilers script
        run: bash Benchmark/multiple-compilers.sh
        working-directory: ${{ github.workspace }}
