name: Validate README Table

on:
  push:
    paths:
    - '.github/workflows/**'
    - 'Checks/**'
    - 'README.md'

jobs:
  validate-readme:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Validate README Table
        run: python .github/utils/ValidateReadmeTable.py
